jobs:
on: push_*
branch: ["master"]
env: Windows-latest
cmd: |
git clone -- https://mirrors.tuna.tsinghua.edu.cn/git/kodi.git
#git remote add tuna https://mirrors.tuna.tsinghua.edu.cn/git/kodi.git
#git remote set-url origin https://mirrors.tuna.tsinghua.edu.cn/git/kodi.git
#git clone https://github.com/electron/electron-quick-start
#cd/ electron-quick-start
#npm install
#npm start https://localhost:8080
