name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: Ubuntu 18.04.5 LTS

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1.8
      with:
        java-version: 1.8.0_265
    - name: Build with Gradle
      run: ./gradlew build
      
